[profile.default]
# Default profile for running tests
retries = 2
slow-timeout = { period = "60s", terminate-after = 2 }

[profile.ci]
# CI profile for faster, more reliable test runs
retries = 3
slow-timeout = { period = "120s", terminate-after = 3 }
failure-output = "immediate-final"
success-output = "final"

[profile.fast]
# Fast profile for quick development feedback
retries = 0
slow-timeout = { period = "30s", terminate-after = 1 }
failure-output = "immediate"

[store]
# Store test results for better reporting
dir = "target/nextest"
