# Cargo-release configuration for VTCode
# See: https://github.com/crate-ci/cargo-release

# Git configuration
push = true
push-remote = "origin"
sign-commit = false
sign-tag = false

# Publishing configuration
registry = "crates.io"
verify = true

# Release settings
shared-version = true
consolidate-commits = true
allow-branch = ["main"]

# Tag configuration
tag = true
tag-name = "v{{version}}"
tag-prefix = ""
tag-message = "Release {{crate_name}} v{{version}}"

# Pre-release hooks (if needed)
pre-release-hook = []

# Features (if needed)
enable-features = []
enable-all-features = false

# Version bumping
dependent-version = "upgrade"
