Output resources/vhs/demo.gif

Require vtcode
Require rustc

Set Shell bash
Set FontSize 15
Set Width 500
Set Height 500
Set Theme '{ "name": "CustomTheme", "background": "#262626", "foreground": "#BFB38F", "selection": "#D99A4E", "cursor": "#BF4545", "black": "#262626", "red": "#BF4545", "green": "#BFB38F", "yellow": "#D99A4E", "blue": "#BFB38F", "magenta": "#D99A4E", "cyan": "#BFB38F", "white": "#BFB38F", "brightBlack": "#262626", "brightRed": "#BF4545", "brightGreen": "#BFB38F", "brightYellow": "#D99A4E", "brightBlue": "#BFB38F", "brightMagenta": "#D99A4E", "brightCyan": "#BFB38F", "brightWhite": "#BFB38F" }'
Set Framerate 60
Set TypingSpeed 30ms


# Introduction
Type "# VT Code - Semantic Coding Agent. Written in Rust. "
Enter
Sleep 1s

# Enter vtcode with specific provider and model
Hide
Type "vtcode"
Enter
Show
Sleep 4s

# Hello
Type "What is this project about"
Enter
Sleep 10s

# Exit vtcode
Type "exit"
Enter
Sleep 2s
